name: venceya # ¡Asegúrate que este nombre sea 'venceya' si ese es el nombre de tu proyecto!
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.8

  # Firebase Core y módulos para VenceYa (Versiones que se sabe que son estables)
  firebase_core: ^3.13.1 # Mantendremos esta versión específica
  firebase_auth: ^5.5.4 # Mantendremos esta versión específica
  cloud_firestore: ^5.6.8 # Mantendremos esta versión específica
  firebase_messaging: ^15.2.6 # Mantendremos esta versión específica
  firebase_analytics: ^11.4.6 # Mantendremos esta versión específica

  # Freezed y JSON Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # GoRouter para navegación
  go_router: ^15.1.3

  # Provider para gestión de estado
  provider: ^6.1.2

  # Notificaciones locales y manejo de zonas horarias
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  intl: ^0.19.0 

  # Google Sign-In
  google_sign_in: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Generadores de código para Freezed y JSON Serialization
  build_runner: ^2.4.15
  freezed: ^2.5.2
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/venceya_logo.png
    - assets/google_logo.png 

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Bold.ttf
          weight: 700