// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ElZJWcRbnuW8OaBghbmtYBfTDVW4EpY',
    appId: '1:914023705727:web:3d2a0a09c11397c721234a',
    messagingSenderId: '914023705727',
    projectId: 'venceya-761cf',
    authDomain: 'venceya-761cf.firebaseapp.com',
    storageBucket: 'venceya-761cf.firebasestorage.app',
    measurementId: 'G-ZYKHEN41V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH_jjL65tDJbBDKkl4_-TtcwkgTvn0ACw',
    appId: '1:914023705727:android:b35db5243d088e2821234a',
    messagingSenderId: '914023705727',
    projectId: 'venceya-761cf',
    storageBucket: 'venceya-761cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBerrua_T8n3AkAXb9GDp9GzGD7F1RMwpM',
    appId: '1:914023705727:ios:cae72c870e1cdf2821234a',
    messagingSenderId: '914023705727',
    projectId: 'venceya-761cf',
    storageBucket: 'venceya-761cf.firebasestorage.app',
    androidClientId: '914023705727-61f55ad9qne1cvqto9q8kfq0aujmokph.apps.googleusercontent.com',
    iosClientId: '914023705727-v7lhgo8icju798qu13gm2kc845p0dfoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.venceya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBerrua_T8n3AkAXb9GDp9GzGD7F1RMwpM',
    appId: '1:914023705727:ios:cae72c870e1cdf2821234a',
    messagingSenderId: '914023705727',
    projectId: 'venceya-761cf',
    storageBucket: 'venceya-761cf.firebasestorage.app',
    androidClientId: '914023705727-61f55ad9qne1cvqto9q8kfq0aujmokph.apps.googleusercontent.com',
    iosClientId: '914023705727-v7lhgo8icju798qu13gm2kc845p0dfoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.venceya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ElZJWcRbnuW8OaBghbmtYBfTDVW4EpY',
    appId: '1:914023705727:web:570bff698047ccea21234a',
    messagingSenderId: '914023705727',
    projectId: 'venceya-761cf',
    authDomain: 'venceya-761cf.firebaseapp.com',
    storageBucket: 'venceya-761cf.firebasestorage.app',
    measurementId: 'G-BPY3CBSZ14',
  );

}